spring:
  datasource:
    username: dbuser
    password: dbuser
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://VDBS;database=Library
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
      hbm2ddl: none
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

